# General Site Settings
title: Dartboard | A Theme to Throw at the Market
description: A Jekyll theme designed for Web Design final project
theme: he-fp-theme/
url: # The base hostname of your site
baseurl: # The subpath of this particular site

# Optional Settings
about: true #Enable/disable the "about" section of the website
header_scroll: false #Enable/disable header to appear when scrolling
ga: false #Enable/disable Google Analytics
discus_identifier: #Your short name for Disqus
google_analytics: #Your Google Analytics identifier, format UA-XXXXXXXX-X
social:
    twitter: #Twitter handle
    facebook: #Facebook handle
    instagram: #Instagram user name
    github: #Github user name
    linkedin: #Linkdein profile ID
    reddit: #Reddit user ID
    email: #Email address

# Build Settings, change at your own risk
markdown: kramdown
permalink: :slug
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
    
include: 
  - _pages    
  
assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts

paginate: 10
paginate_path: "/page/:num"
    
sass:
  sass_dir: _sass
  style: compressed
  
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
